import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import HeaderImage from "@/components/HeaderImage";
import Slider1 from "@/components/Slider1";
import styles from "./style.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <div className={styles.zentai}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main className={styles.mainbox}>
          <HeaderImage />
          <Slider1 />
        </main>
        <Footer />
      </div>
    </>
  );
}
